[phases]
setup = { nixPkgs = ["python39", "nodejs"] }

[phases.install]
cmds = [
    "python3 -m ensurepip",
    "python3 -m pip install -r backend/requirements.txt"
]

[start]
cmd = "cd backend && python3 main.py"