[phases]
setup = { 
    nixPkgs = ["python39", "nodejs-18.x", "pip"] 
}

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r backend/requirements.txt",
    "cd frontend && (npm install || yarn install || true)"
]

[phases.build]
cmds = [
    "cd frontend && (npm run build || yarn build || true)"
]

[start]
cmd = "cd backend && python main.py || python -m uvicorn main:app --host 0.0.0.0 --port $PORT"

[build]
baseImage = "ubuntu:20.04"