[phases]
setup = { nixPkgs = ["python39", "nodejs"] }
install = [
    "pip install -r backend/requirements.txt",
    "cd frontend && npm install || yarn install || echo 'No frontend dependencies found'"
]
build = [
    "cd frontend && npm run build || yarn build || echo 'No frontend build needed'"
]

[start]
cmd = "cd backend && python main.py || python -m uvicorn main:app --host 0.0.0.0 --port $PORT"